-- Class 101 AI Hub — Seed real franchise locations (pulled from class101.com/locations).
alter table public.franchises add column if not exists city text;
alter table public.franchises add column if not exists state text;

insert into public.franchises (name, slug, city, state) values
  ('Class 101 — Camarillo, CA', 'camarilloca', 'Oak Park', 'CA'),
  ('Class 101 — Alliance, TX', 'alliancetx', 'Alliance', 'TX'),
  ('Class 101 — Atlanta Northwest', 'atlantanorthwest', 'Atlanta', 'GA'),
  ('Class 101 — Blackwater', 'blackwater', 'Crestview', 'FL'),
  ('Class 101 — Bloomington IN', 'bloomingtonin', 'Bloomington', 'IN'),
  ('Class 101 — Brandon FL', 'brandonfl', 'Brandon', 'FL'),
  ('Class 101 — Brazos County', 'brazoscountytx', 'Bryan', 'TX'),
  ('Class 101 — Carmel IN', 'carmelin', 'Carmel', 'IN'),
  ('Class 101 — Central WI', 'centralwi', 'Wausau', 'WI'),
  ('Class 101 — Charleston, SC', 'charlestonsc', 'Charleston', 'SC'),
  ('Class 101 — Chattanooga', 'chattanoogatn', 'Chattanooga', 'TN'),
  ('Class 101 — Chelmsford MA', 'chelmsfordma', 'North Chelmsford', 'MA'),
  ('Class 101 — Chesapeake VA', 'chesapeakeva', 'Chesapeake', 'VA'),
  ('Class 101 — Cleveland Oh Southeast', 'clevelandohsoutheast', 'Chagrin Falls', 'OH'),
  ('Class 101 — Colorado Springs', 'coloradosprings', null, null),
  ('Class 101 — Conejo Valley CA', 'conejovalleyca', 'Westlake Village', 'CA'),
  ('Class 101 — Coral Gables, FL', 'southmiamifl', 'Coral Gables', 'FL'),
  ('Class 101 — Cypress', 'cypresstx', null, null),
  ('Class 101 — Dayton OH South', 'daytonohsouth', 'Springboro', 'OH'),
  ('Class 101 — Denton-Lake Cities, TX', 'dentonlakecities', 'Corinth', 'TX'),
  ('Class 101 — Denver West', 'denver-west', 'Denver West', 'CO'),
  ('Class 101 — Douglas County CO', 'douglascountyco', 'Castle Pines', 'CO'),
  ('Class 101 — Downers Grove, IL', 'chicagowesternsuburbs', 'Downers Grove', 'IL'),
  ('Class 101 — Eastern KY', 'easternky', 'London', 'KY'),
  ('Class 101 — Evergreen Park, IL', 'evergreenparkil', 'Evergreen Park', 'IL'),
  ('Class 101 — Flower Mound, TX', 'flowermoundtx', 'Flower Mound', 'TX'),
  ('Class 101 — Fort Mill, SC', 'fortmillsc', null, null),
  ('Class 101 — Franklin TN', 'franklintn', 'Franklin', 'TN'),
  ('Class 101 — Ft. Myers. FL', 'ftmyersfl', 'Ft. Myers', 'FL'),
  ('Class 101 — Grand Prairie TX', 'grandprairietx', 'Grand Prairie', 'TX'),
  ('Class 101 — Greater Rochester NY East', 'greaterrochesterny', 'Victor', 'NY'),
  ('Class 101 — Hawthorne, CA', 'hawthorneca', 'Hawthorne', 'CA'),
  ('Class 101 — Houston Heights, TX', 'houstonheightstx', 'Houston', 'TX'),
  ('Class 101 — Irvine, CA', 'irvineca', 'Irvine', 'CA'),
  ('Class 101 — Irving TX', 'irvingtx', 'Irving', 'TX'),
  ('Class 101 — Katy TX', 'katytx', 'Katy', 'TX'),
  ('Class 101 — La Mesa, CA', 'lamesaca', 'La Mesa', 'CA'),
  ('Class 101 — Lake Nona, FL', 'lakenonafl', 'Lake Nona', 'FL'),
  ('Class 101 — Leesburg, VA', 'leesburgva', 'Hawthorne', 'CA'),
  ('Class 101 — Lexington KY', 'lexingtonky', 'Lexington', 'KY'),
  ('Class 101 — Mesa-Gilbert', 'mesagilbert', 'Mesa', 'AZ'),
  ('Class 101 — Mid Cities TX', 'midcitiestx', 'North Richland Hills', 'TX'),
  ('Class 101 — Midland, TX', 'midlandtx', 'Midland', 'TX'),
  ('Class 101 — Missouri City, TX', 'missouricitytx', 'Missouri City', 'TX'),
  ('Class 101 — Mobile AL', 'mobileal', null, null),
  ('Class 101 — Monmouth County NJ', 'monmouthcountynj', null, null),
  ('Class 101 — Nashville TN', 'nashvilletn', 'Nashville', 'TN'),
  ('Class 101 — New Braunfels, TX', 'newbraunfelstx', 'New Braunfels', 'TX'),
  ('Class 101 — NJ Bergen West', 'njbergenwest', 'Ho-Ho-Kus', 'NJ'),
  ('Class 101 — Norman OK', 'normanok', 'Norman', 'OK'),
  ('Class 101 — North Palm Beach, FL', 'northpalmbeachfl', 'Jupiter', 'FL'),
  ('Class 101 — Northeast Cincinnati', 'northeastcincinnati', 'West Chester', 'OH'),
  ('Class 101 — Northwest Omaha, NE', 'northwestomahane', 'Omaha', 'NE'),
  ('Class 101 — O''Fallon, IL', 'ofallonil', 'O''Fallon', 'IL'),
  ('Class 101 — Overland Park, KS', 'overlandpark', 'Overland Park', 'KS'),
  ('Class 101 — Pittsburgh PA', 'pittsburghpaeast', 'Irwin', 'PA'),
  ('Class 101 — Prosper-Frisco', 'prosperfriscotx', 'Prosper-Frisco', 'TX'),
  ('Class 101 — San Francisco, CA', 'sanfranciscoca', 'San Francisco', 'CA'),
  ('Class 101 — Sandia Heights', 'sandiaheightsnm', 'Albuquerque', 'NM'),
  ('Class 101 — Savannah GA', 'savannahga', 'Savannah', 'GA'),
  ('Class 101 — Sherman Oaks, CA', 'shermanoaksca', 'Sherman Oaks', 'CA'),
  ('Class 101 — South Oakland', 'southoaklandmi', 'Birmingham', 'MI'),
  ('Class 101 — South Riding, VA', 'southridingva', 'South Riding', 'VA'),
  ('Class 101 — Southwest Missouri', 'southwestmissouri', 'Springfield', 'MO'),
  ('Class 101 — Sugar Land, TX', 'sugarlandtx', 'Sugar Land', 'TX'),
  ('Class 101 — Suwanee-Duluth', 'suwaneeduluth', 'Duluth', 'GA'),
  ('Class 101 — The Woodlands', 'thewoodlandstx', 'The Woodlands', 'TX'),
  ('Class 101 — Treasure Coast FL', 'treasurecoastfl', 'Palm City', 'FL'),
  ('Class 101 — Tupelo MS', 'tupeloms', 'Tupelo', 'MS'),
  ('Class 101 — Waco, TX', 'wacotexas', 'Woodway', 'TX'),
  ('Class 101 — Wake County NC', 'wakecountync', 'Cary', 'NC'),
  ('Class 101 — West Hollywood, CA', 'westhollywoodca', 'West Hollywood', 'CA'),
  ('Class 101 — West Linn, OR', 'westlinnor', 'West Linn', 'OR'),
  ('Class 101 — West St. Louis County MO', 'weststlouiscountymo', 'Ballwin', 'MO'),
  ('Class 101 — Western KY', 'westernkentucky', 'Madisonville', 'KY'),
  ('Class 101 — Westerville OH', 'westervilleoh', 'Westerville', 'OH'),
  ('Class 101 — Williamson County North, TX', 'williamsoncountynorthtx', null, null),
  ('Class 101 — Wilmington NC', 'wilmingtonnc', 'Wilmington', 'NC'),
  ('Class 101 — Peachtree City, GA', 'peachtreecityga', 'Fayetteville', 'GA'),
  ('Class 101 — San Antonio West, TX', 'sanantoniowesttx', 'San Antonio', 'TX')
on conflict (slug) do update set name = excluded.name, city = excluded.city, state = excluded.state;

-- Add the current single user as counselor in 3 demo locations so the switcher activates.
with target as (select id, role from auth.users join (values ('owner'::text)) v(role) on true limit 1)
insert into public.memberships (user_id, franchise_id, role)
select t.id, f.id, 'counselor'
  from target t,
       public.franchises f
 where f.slug in ('lexingtonky', 'atlantanorthwest', 'carmelin')
on conflict do nothing;
